name: Android CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle
      - name: Create local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties
      - name: Create google-services.json
        run: cat /home/runner/work/JOBIS-DSM-ANDROID/JOBIS-DSM-ANDROID/presentation/google-services.json | base64
      - name: Putting google-services.json data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/JOBIS-DSM-ANDROID/JOBIS-DSM-ANDROID/presentation/google-services.json
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run test
        run: ./gradlew test
